### ISSUE TITLE
Issue with spotify artist search

### ISSUE THREAD

**Issue by HyungnaLim** [HyungnaLim/ITEC2905-Project3#12]
When the artist search term is given, Spotify API usually get information about the closest artist by search term.
For example, when you search this random string "sdcjhbaskd", the result is as below;
![image](https://github.com/user-attachments/assets/44a27ce0-a617-4784-8ced-cc0b90d581cd)

It can be frustrating if we are building an app where the search term and artist must match,
but considering that the app is called "discover artist", I think this is interesting to have.
Maybe we should prompt user about this on our main page? just an idea!

**Comment by rwalk651** [comment]
Sounds like a cool feature to add, what kind of prompt did you have in mind?

**Comment by LTizzle1212** [comment]
Potentially with some type of warning about this or stating "When searching this will search in Spotify as closest to the search term" or something along those lines
