### ISSUE TITLE
html in Spotify track info

### ISSUE THREAD

**Issue by rwalk651** [HyungnaLim/ITEC2905-Project3#9]
https://github.com/HyungnaLim/ITEC2905-Project3/blob/f9be917c087dda0d62e5b80c8d0b04c8c7869c84/apis/spotify_api.py#L72-L77

@HyungnaLim When saving to the database these `<br>` etc. values are included. I think they should be moved to search.html.

![image](https://github.com/user-attachments/assets/8c230cc3-9481-4928-8ca0-c0a782a57210)

**Comment by HyungnaLim** [comment]
Is there any way to use Spotify.tracks instead of tracks_str method? I created tracks_str method only to display track info nicely in search_result html template. Using .tracks will return the list of 3 dictionaries, not a string version. It should be more suitable to be saved in a database.

**Comment by rwalk651** [comment]
Yeah I can, this might come as an issue later though. Like if someone changes the layout to search_results.html and is unaware of how the data is being returned, the tracks will have extra breaks. I'll throw my suggestion down below, but yeah this isn't really a huge issue, just something I ran into.

app.py:
```
return render_template('search_result.html',
                           ...
                           artist_track_one=artist_info.tracks[0],
                           artist_track_two=artist_info.tracks[1],
                           artist_track_three=artist_info.tracks[2],
                           ...
```
search_results.html:
```
<h2>Top Tracks of {{ artist_name }}</h2>
<p>
    {{ artist_track_one.title }}<br>
    {{ artist_track_one.album }}<br>
    {{ artist_track_one.release_date }}<br>
    <a href=artist_track_one.spotify_url>Listen on Spotify</a><br><br>

    {{ artist_track_two.title }}<br>
    {{ artist_track_two.album }}<br>
    {{ artist_track_two.release_date }}<br>
    <a href=artist_track_two.spotify_url>Listen on Spotify</a><br><br>

    {{ artist_track_three.title }}<br>
    {{ artist_track_three.album }}<br>
    {{ artist_track_three.release_date }}<br>
    <a href=artist_track_three.spotify_url>Listen on Spotify</a><br><br>
</p>
<hr>
```
